services:
    sio_test:
        user: app
        build:
            context: .
            args:
                USER_ID: ${USER_ID:-1000}
        ports:
            - "8337:8337"
        volumes:
            - .:/app:rw
        environment:
            - APP_ENV=dev
        depends_on:
            - database
        networks:
            - symfony_app
    database:
        image: postgres:${POSTGRES_VERSION:-13}-alpine
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-app}
            # You should definitely change the password in production
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secretive}
            POSTGRES_USER: ${POSTGRES_USER:-symfony}
        volumes:
            - db-data:/var/lib/postgresql/data:rw
        networks:
            - symfony_app
volumes:
    db-data:
networks:
    symfony_app: